routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

# User Login
Route::get('/sign-in', 'UserLoginController@showUserLoginForm')->name('sign-in');
Route::post('/sign-in', 'UserLoginController@userLogin')->name('user.submit.login');

Route::post('/logout', 'UserLoginController@userLogout')->name('user.logout');

# User Routes
Route::name('front.')->group(function () {
    Route::get('/', 'HomeController@index')->name('homepage');
    Route::get('/album/{album}', 'HomeController@showAlbum')->name('show.album');
    Route::get('/register', 'UserController@showUserRegister')->middleware('guest:web')->name('show.register');
    Route::post('/register', 'UserController@register')->name('register');

    Route::group(['middleware' => ['auth', 'CheckUserActive']], function (){
        Route::get('/profile', 'UserController@profile')->name('profile');
        Route::get('/my-albums', 'UserController@myAlbums')->name('my-albums');
        Route::get('/my-albums/{album}/edit', 'UserController@singleAlbum')->name('single.album');
        Route::post('/editAlbum/{album}', 'UserController@editAlbum')->name('user.edit.album');
        Route::post('/addImageToAlbum/{album}', 'UserController@addImageToAlbum')->name('user.album.add');
        Route::post('/delAlbum/{album}', 'UserController@delAlbum')->name('user.album.del');
        Route::post('/createNewAlbum/', 'UserController@createNewAlbum')->name('user.album.create');
        Route::post('/delImageFromAlbum', 'UserController@delImageFromAlbum')->name('user.remove.image');
        Route::get('/my-albums/{album}', 'UserController@getAlbumImages')->name('getAlbumImages');
        Route::post('/updateProfile', 'UserController@updateProfile')->name('updateProfile');
        Route::post('/changeUserPassword', 'UserController@changeUserPassword')->name('changeUserPassword');
    });
});

Route::get('/home', 'HomeController@index')->name('home');

app/Models/User.php
<?php

namespace App\Models;

use App\Crud\Crud;
use Exception;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable, SoftDeletes;

    protected $guarded = ['id'];

    protected $hidden = ['password', 'remember_token'];

    protected $casts = ['email_verified_at' => 'datetime', 'status' => 'boolean'];

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    public function getImageUrlAttribute()
    {
        return getDefaultImage($this, 'users');
    }

    public function token()
    {
        return $this->morphOne(Token::class, 'tokenable');
    }

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }

    public function fcm()
    {
        return $this->morphOne(Fcm::class,'fcmable');
    }

    public function albums()
    {
        return $this->hasMany(Album::class,'user_id', 'id');
    }

    public function setStatusAttribute($value)
    {
        if (is_null($value)) $value = false;

        $this->attributes['status'] = (boolean) $value;
    }

    public static function changeStatus($request)
    {
        return Crud::setStatus(self::class, $request);
    }

    public static function createUser($request)
    {
        return Crud::store(self::class, $request, true);
    }

    public static function updateUser($request, $currentUser)
    {
        return Crud::update(self::class, $request, $currentUser, true);
    }

    public static function deleteUser($request)
    {
        return Crud::delete(self::class, $request->id);
    }

    public static function sendUserMessage($request)
    {
        return Crud::sendUserMessage($request);
    }

    public static function register($request)
    {
        try
        {
            Auth::login(User::create([
                "name"     => $request->name,
                "email"    => $request->email,
                "password" => $request->password,
            ]));

            return redirect('/');
        }
        catch (Exception $e)
        {
            return back()->with('danger', $e->getMessage());
        }
    }

    public static function getInSelectForm()
    {
        return Crud::getModelsInSelectedForm(self::class,'name');
    }
}

app/Http/Controllers/Back/AdminController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\BASE_CONTROLLER;
use App\Http\Requests;
use App\Models\Admin;
use App\Models\Role;
use Illuminate\Http\Request;
use App\Exports\AdminsExport;
use Illuminate\Support\Facades\Auth;

class AdminController extends BASE_CONTROLLER
{
    public function __construct()
    {
        parent::__construct('admin', Admin::class, new AdminsExport);
    }

    public function index()
    {
        return view('Back.Admins.index', ['admins' => Admin::where('role_id', '!=', 1)->orWhere('role_id', '=', null)->get()]);
    }

    public function showAdminMessage($id)
    {
        if (!$admin = Admin::find($id)) return response()->json(['requestStatus' => false, 'message' => trans('responseMessages.product-not-exist')]);

        return view('Back.Admins.showAdminMailSendModal', compact('admin'))->render();
    }

    public function sendAdminMessage(Request $request)
    {
        return Admin::sendAdminMessage($request);
    }

    public function showAdmin(Admin $admin)
    {
        return view('Back.Admins.show', compact('admin'));
    }

    public function home()
    {
        return view('Back.index');
    }

    public function AdminUpdateProfile(Requests\Back\EditAdminProfileRequest $request)
    {
        $adminData = $request->except(['_token', 'submit']);

        $currentAdmin = Admin::find($adminData['admin_id']);

        return Admin::updateAdmin(arr()->except($adminData, ['admin_id']), $currentAdmin);
    }

    public function adminProfile()
    {
        return view('Back.Admins.profile', ['admin' => Auth::guard('admin')->user()]);
    }

    public function create()
    {
        return view('Back.Crud.create', ['roles' => Role::getInSelectForm(), 'model' => 'admin']);
    }

    public function store(Requests\Back\CreateAdminRequest $request)
    {
        return Admin::createAdmin($request);
    }

    public function edit($id)
    {
        return view('Back.Crud.edit', ['currentModel' => Admin::findOrFail($id), 'roles' => Role::getInSelectForm(), 'model' => 'admin']);
    }

    public function update(Requests\Back\EditAdminRequest $request, $id)
    {
        return Admin::updateAdmin($request, Admin::find($id));
    }

    public function DeleteAdmin(Request $request)
    {
        return Admin::deleteAdmin($request);
    }
}

app/Http/Controllers/Back/AlbumController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\BASE_CONTROLLER;
use App\Http\Requests;
use App\Models\Album;
use App\Models\User;
use App\Exports\AlbumsExport;
use Illuminate\Http\Request;

class AlbumController extends BASE_CONTROLLER
{
    public function __construct()
    {
        parent::__construct('album', Album::class, new AlbumsExport);
    }

    public function create()
    {
        return view('Back.Crud.create', ['model' => 'album', 'users' => User::getInSelectForm(), 'types' => Album::types()]);
    }

    public function showAlbum(Album $album)
    {
        return view('Back.Albums.show', compact('album'));
    }

    public function edit($id)
    {
        return view('Back.Crud.edit', ['currentModel' => Album::findOrFail($id), 'model' => 'album', 'users' => User::getInSelectForm(), 'types' => Album::types()]);
    }

    public function store(Requests\Back\CreateAlbumRequest $request)
    {
        return Album::createAlbum($request);
    }

    public function update(Requests\Back\EditAlbumRequest $request, $id)
    {
        return Album::updateAlbum($request, Album::find($id));
    }

    public function DeleteAlbum(Request $request)
    {
        return Album::deleteAlbum($request);
    }
}

app/Http/Controllers/Back/ContactController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Requests;
use App\Models\Contact;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Exports\ContactsExport;
use Maatwebsite\Excel\Facades\Excel;

class ContactController extends Controller
{
    public function Contacts()
    {
        return view('Back.Contacts.contacts', ['contacts' => Contact::all()]);
    }

    public function showMessageDetails($id)
    {
        if (!$message = Contact::find($id)) return response()->json(['requestStatus' => false, 'message' => trans('responseMessages.product-not-exist')]);

        return view('Back.Contacts.messageDetailsModal', compact('message'))->render();
    }

    public function sendUserMessage($id)
    {
        if (!$message = Contact::find($id)) return response()->json(['requestStatus' => false, 'message' => trans('back.message-not-exists')]);

        return view('Back.Contacts.sendUserMessageModal', compact('message'));
    }

    public function SendUserReplayMessage(Request $request)
    {
        return Contact::sendUserReplayMessage($request);
    }

    public function ContactsExport(Request $request)
    {
        return Excel::download(new ContactsExport, 'contacts.xlsx');
    }

    public function DeleteContact(Request $request)
    {
        return Contact::deleteMessage($request);
    }
}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\Agency;
use App\Models\BankTransfer;
use App\Models\Service;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        $users = User::latest()->get();

        return view('Back.index', [
            'latest_users' => $users->take(4),
            'days'         => getCollectionBerDayCount($users),
//            'months'       => getCollectionBerMonthCount(BankTransfer::whereStatus(1)->groupBy(['package_id', 'created_at'])->selectRaw('sum(price) as sum, created_at')->get()),
            'users'        => $users
        ]);
    }
}

app/Http/Controllers/Back/PhotoController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\BASE_CONTROLLER;
use App\Http\Requests;
use App\Models\Album;
use App\Models\Photo;
use App\Models\User;
use App\Exports\PhotosExport;
use Illuminate\Http\Request;

class PhotoController extends BASE_CONTROLLER
{
    public function __construct()
    {
        parent::__construct('photo', Photo::class, new PhotosExport);
    }

    public function create()
    {
        return view('Back.Crud.create', [
            'model'  => 'photo',
            'albums' => Album::getInSelectForm(),
        ]);
    }

    public function edit($id)
    {
        return view('Back.Crud.edit', [
            'currentModel' => Photo::findOrFail($id),
            'model'        => 'photo',
            'albums'       => Album::getInSelectForm(),
        ]);
    }

    public function store(Requests\Back\CreatePhotoRequest $request)
    {
        return Photo::createPhoto($request);
    }

    public function update(Requests\Back\EditPhotoRequest $request, $id)
    {
        return Photo::updatePhoto($request, Photo::find($id));
    }

    public function DeletePhoto(Request $request)
    {
        return Photo::deletePhoto($request);
    }
}

app/Http/Controllers/Back/RoleController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\BASE_CONTROLLER;
use App\Http\Requests;
use App\Models\Role;
use App\Exports\RolesExport;
use Illuminate\Http\Request;

class RoleController extends BASE_CONTROLLER
{
    public function __construct()
    {
        parent::__construct('role', Role::class, new RolesExport);
    }

    public function index()
    {
        return view('Back.Roles.index', ['roles' => Role::orderBy('id', 'desc')->where('id', '!=', 1)->get()]);
    }

    public function store(Requests\Back\CreateRoleRequest $request)
    {
        return Role::createRole($request);
    }

    public function update(Requests\Back\EditRoleRequest $request, $id)
    {
        return Role::updateRole($request, Role::find($id));
    }

    public function DeleteRole(Request $request)
    {
        return Role::deleteRole($request);
    }
}

app/Http/Controllers/Back/SettingController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Requests;
use App\Models\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Exports\SettingsExport;
use Maatwebsite\Excel\Facades\Excel;

class SettingController extends Controller
{
    public function index()
    {
        return view('Back.Settings.index', ['settings' => Setting::all()]);
    }

    public function create()
    {
        return view('Back.Settings.create');
    }

    public function export(Request $request)
    {
        return Excel::download(new SettingsExport, 'settings.xlsx');
    }

    public function store(Requests\Back\CreateSettingRequest $request)
    {
        return Setting::createSetting($request);
    }

    public function edit(Setting $setting)
    {
        return view('Back.Settings.edit', compact('setting'));
    }

    public function update(Requests\Back\EditSettingRequest $request, $id)
    {
        return Setting::updateSetting($request, Setting::find($id));
    }

    public function UpdateAll(Request $request)
    {
        return Setting::updateAll($request);
    }
}

app/Http/Controllers/Back/UserController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\BASE_CONTROLLER;
use App\Http\Requests;
use App\Models\City;
use App\Models\User;
use Exception;
use Illuminate\Http\Request;
use App\Exports\UsersExport;

class UserController extends BASE_CONTROLLER
{
    public function __construct()
    {
        parent::__construct('user', User::class, new UsersExport);
    }

    public function showUserMessage($id)
    {
        if (!$user = User::find($id)) return response()->json(['requestStatus' => false, 'message' => trans('responseMessages.product-not-exist')]);

        return view('Back.Users.sendUserMessageModal', compact('user'))->render();
    }

    public function forceDelete($id)
    {
        modelForceDelete(User::class, $id, true);

        return back()->with('success', translated('remove','user'));
    }

    public function sendUserMessage(Request $request)
    {
        return User::sendUserMessage($request);
    }

    public function showUser(User $user)
    {
        return view('Back.Users.show', compact('user'));
    }

    public function store(Requests\Back\CreateUserRequest $request)
    {
        return User::createUser($request);
    }

    public function update(Requests\Back\EditUserRequest $request, $id)
    {
        return User::updateUser($request, User::find($id));
    }

    public function DeleteUser(Request $request)
    {
        return User::deleteUser($request);
    }
}

resources/views/Back/Users/form.blade.php
<div class="form-group">
    <x-form-inputs type="text" name="name" :slug="trans('back.form-name')" :errors="$errors"></x-form-inputs>
</div>

<div class="form-group">
    <x-form-inputs type="email" name="email" :slug="trans('back.form-email')" :errors="$errors"></x-form-inputs>
</div>

@if(Route::is('users.create'))
	<div class="form-group">
        <x-form-inputs type="password" name="password" :slug="trans('back.form-password')" :errors="$errors"></x-form-inputs>
	</div>
	<div class="form-group">
        <x-form-inputs type="password_confirmation" name="password" :slug="trans('back.form-password')" :errors="$errors"></x-form-inputs>
	</div>
@endif

<div class="form-group">
    <x-form-inputs type="image" name="image" :slug="trans('back.form-image')" :errors="$errors"></x-form-inputs>
    <div class="col-xs-6">
		<div class="img-container">
			<img id="viewImage" class="img-responsive" width="90" height="90" src="{{ isset($currentModel) ? $currentModel->image_url : '' }}" alt=""/>
		</div>
	</div>
</div>

<div class="form-group">
    <x-switch-input :model="$currentModel ?? null"></x-switch-input>
</div>

@section('scripts')
    <script>$('input[name=image]').on('change', function(){readURL(this);});</script>
@stop

resources/views/Back/Users/index.blade.php
<x-model-index-page model="user" modelType="male">
    <table class="table datatable-basic" id="users" style="font-size: 16px;">
        <thead>
        <tr>
            <th>#</th>
            <th>@lang('back.form-name')</th>
            <th>@lang('back.form-status')</th>
            <th>@lang('back.since')</th>
            <th>@lang('back.updated_at')</th>
            <th class="text-center">@lang('back.form-actions')</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr id="user-row-{{ $user->id }}">
                <td>{{ $user->id }}</td>

                <td><a href="{{ route('users.show-user', $user->id) }}"> {{ $user->name ?? trans('back.no-value') }}</a></td>

                @include('Back.includes.changeModelStatus', ['status' => $user->status, 'id' => $user->id])

                <td>{{ $user->created_at->diffForHumans() }}</td>

                <td>{{ $user->updated_at->diffForHumans() }}</td>

                <td class="text-center">
                    @include('Back.includes.edit-delete', ['route' => 'users', 'model' => $user])
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <x-slot name="scripts">
        <script>
            $('table#users').on('click', 'a.show-user-mail-sending-btn', function () {
                let clickedMessageAnchor = $(this);
                let ajaxUrl = clickedMessageAnchor.attr('href');
                let siteModal = $('div#site-modals');
                $.ajax({
                    type: 'GET',
                    url: ajaxUrl,
                    success: function (response) {
                        siteModal.html(response);
                        if (response.requestStatus && response.requestStatus === false) {
                            siteModal.html('');
                        } else {
                            $('#view_show_user_send_message').modal('show');
                        }
                    },
                    error: (x) => crud_handle_server_errors(x),
                });
                return false;
            });
        </script>
    </x-slot>
</x-model-index-page>

resources/views/Back/Users/sendUserMessageModal.blade.php
<div id="view_show_user_send_message" class="modal fade">
    <div class="modal-dialog">
        <form action="{{route('users.send.message')}}" method="post">
            <div class="modal-content" dir="{{direction()}}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h1 class="modal-title">@lang('back.send-a-message')</h1>
                </div>

                <div class="modal-body">
                    @csrf
                    <input type="hidden" name="email" value="{{$user->email}}" id="email">
                    <textarea style="resize: vertical;" name="message" class="form-control" id="message" cols="30" rows="10"></textarea>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">@lang('back.close')</button>
                    <button type="submit" name="submit" class="btn btn-primary">@lang('back.send')</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/Back/Users/show.blade.php
@extends('Back.layouts.master')

@section('title', $user->name)

@section('content')
    <x-page-show-header model="user" :title="$user->name"></x-page-show-header>

    <div class="content">
        <div class="row">
            @include('includes.flash')
            <div class="col-md-8 col-md-offset-2">
                <!-- Basic table -->
                <div class="panel panel-primary">
                    <div class="panel-heading">@lang('back.user')</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-3" style="float: {{ floating('right', 'left') }}">
                                <div class="thumbnail">
                                    <div class="thumb">
                                        <img style="width: 300px;height: 200px;" src="{{ $user->image_url }}" alt="">
                                        <div class="caption-overflow">
                                            <span>
                                                <a href="{{ route('users.edit', $user->id) }}"
                                                   class="btn btn-info btn-sm">@lang('back.edit')</a>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="caption">
                                        <h6 class="text-semibold no-margin-top" title="{{ $user->name }}">
                                            {{ ucwords(str()->limit($user->name, 30, '...')) }}
                                        </h6>
                                    </div>
                                </div>
                                <div class="lead">
                                    <button class="btn btn-success btn-block" data-toggle="modal" data-target="#view_show_user_send_notification">@lang('back.send-notification')
                                        <i class="icon-bell-check"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-9" style="float: {{ floating('left', 'right') }}">
                                <div class="well">
                                    <dl dir="{{ direction() }}">
                                        <dt>@lang('back.form-email')</dt>
                                        <dd>{{ $user->email ?? trans('back.no-value') }}</dd>

                                        <dt>@lang('back.form-status')</dt>
                                        <dd>
                                            @if($user->status == 1) <span
                                                class="label label-success">@lang('back.active')</span>
                                            @else <span class="label label-danger">@lang('back.disactive')</span>
                                            @endif
                                        </dd>

                                        <dt>@lang('back.since')</dt>
                                        <dd>{{ $user->created_at->diffForHumans() }}</dd>
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /basic table -->
            </div>

            <div class="col-md-8 col-md-offset-2">
                <!-- Latest posts -->
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h6 class="panel-title">@lang('back.albums')</h6>
                        <div class="heading-elements">
                            <ul class="icons-list">
                                <li><a data-action="collapse"></a></li>
                                <li><a data-action="reload"></a></li>
                                <li><a data-action="close"></a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="panel-body">
                        <div class="row">
                            @forelse($user->albums->chunk(2) as $chunks)
                                <div class="col-lg-6">
                                    <ul class="media-list content-group">
                                        @foreach($chunks as $album)
                                            <li class="media stack-media-on-mobile">
                                                <div class="media-left">
                                                    <div class="thumb">
                                                        <a href="{{ route('albums.show-album', $album->id) }}">
                                                            <img src="{{ $album->image_url ?? defaultImage() }}" class="img-responsive img-rounded media-preview" alt="">
                                                        </a>
                                                    </div>
                                                </div>

                                                <div class="media-body">
                                                    <h6 class="media-heading"><a href="{{ route('albums.show-album', $album->id) }}">{{ ucwords($album->name ?? trans('back.no-value')) }}</a></h6>
                                                    <ul class="list-inline list-inline-separate text-muted mb-5">
                                                        <li><i class="icon-microscope position-left"></i> {{ ucwords($user->name  ?? trans('back.no-value')) }}</li>
                                                        <li>{{ $album->created_at->diffForHumans() }}</li>
                                                    </ul>
                                                </div>
                                            </li>
                                        @endforeach
                                    </ul>
                                </div>
                            @empty
                                <div class="alert alert-info text-center">@lang('back.no-value')</div>
                            @endforelse
                        </div>
                    </div>
                </div>
                <!-- /latest posts -->
            </div>
        </div>
    </div>

    <div id="view_show_user_send_notification" class="modal fade">
        <div class="modal-dialog">
            <form action="{{ route('users.send-notification') }}" method="post">
                <div class="modal-content" dir="{{direction()}}">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h1 class="modal-title">@lang('back.send-a-message')</h1>
                    </div>

                    <div class="modal-body">
                        @csrf
                        <input type="hidden" name="user_id" value="{{ $user->id }}">
                        <div class="form-group @error('title') has-error @enderror">
                            <label for="title">@lang('back.form-title')</label>
                            <input type="text" name="title" id="title" class="form-control">
                            @error('title') <span
                                style="color: #d84315"><strong>{{ $message }}</strong></span> @enderror
                        </div>
                        <div class="form-group @error('title') has-error @enderror">
                            <label for="body">@lang('back.form-body')</label>
                            <input type="text" name="body" id="body" class="form-control">
                            @error('body') <span style="color: #d84315"><strong>{{ $message }}</strong></span> @enderror
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-link" data-dismiss="modal">@lang('back.close')</button>
                        <button type="submit" name="submit" class="btn btn-primary">@lang('back.send')</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@stop

resources/views/Back/Users/trashed.blade.php
@extends('Back.layouts.master')

@section('title', trans('back.trashed'))

@section('content')
    <x-page-header model="user" type="trashes"></x-page-header>

    <!-- Basic datatable -->
    <div class="panel panel-flat" dir="{{ direction() }}" style="margin: 20px;">
        @include('includes.flash')

        <div class="panel-heading">
            <x-trashed-table-head table="users" :collection="$trashes"></x-trashed-table-head>
        </div>

        <table class="table datatable-basic" id="users" style="font-size: 16px;">
            <thead>
            <tr>
                <th>#</th>
                <th>@lang('back.form-name')</th>
                <th>@lang('back.form-image')</th>
                <th>@lang('back.form-status')</th>
                <th>@lang('back.since')</th>
                <th class="text-center">@lang('back.form-actions')</th>
            </tr>
            </thead>
            <tbody>
            @foreach($trashes as $key => $user)
                <tr id="user-row-{{ $user->id }}">
                    <td>{{ $key+1 }}</td>

                    <td>{{ $user->name ?? trans('back.no-value') }}</td>

                    <td><img width="60" height="60" class="img-circle" src="{{ $user->image_url }}" alt=""></td>

                    <td>
                        @if($user->status == 1)
                            <label class="label label-success">Active</label>
                        @else
                            <label class="label label-danger">Didactive</label>
                        @endif
                    </td>

                    <td>{{ $user->created_at->diffForHumans() }}</td>

                    <td class="text-center">
                        <x-trash-menu table="users" :model="$user"></x-trash-menu>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic datatable -->
@stop